### ISSUE TITLE
Show NVD instead of JVN on CVE details page by default

### ISSUE THREAD

**Issue by freerko** [usiusi360/vulsrepo#25]
Hi,

would it be possible to show the NVD info instead of JVN on the CVE details page by default? For all CVEs I checked I got more information on the NVD screen in comparision to the JVN screen. This would save a click every time I open a CVE detail page :)

Thanks!

**Comment by usiusi360** [comment]
Try to implement a switch for the priority setting.
Please give me some time.

**Comment by usiusi360** [comment]
Changed to the end to store the selected tab.
Please check it.
