### ISSUE TITLE
Load error! (parsererror)

### ISSUE THREAD

**Issue by Colbize** [usiusi360/vulsrepo#49]
Followed install instructions, unable to load reports.  Getting `Load error! (parsererror)` in select file.  

```
cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
```

Console output:
```
jquery.dynatree.min.js:3 13:55:51.924 - appendAjax failed: parsererror :
 
Object {readyState: 4, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
 
 SyntaxError: Unexpected token # in JSON at position 0
    at parse (<anonymous>)
    at Qb (jquery-3.2.0.min.js:4)
    at A (jquery-3.2.0.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.2.0.min.js:4)
```

**Comment by usiusi360** [comment]
### There are two possible causes
1. The Apache process is not authorized to access vuls JSON file.
2. CGI can not be executed normally.

### I want you to investigate the cause by the following method.

1. Run as a vuls user.  JSON will be returned if normal.
```
$ ./dist/cgi/getfilelist.cgi
Content-Type: application/json; charset=UTF-8

[{"isFolder":"true","children":[{"url":"/20170301/rhel7.json","title":"rhel7.json"}],"title":"20170301"}]
```

2. Access to http://<serverIP>/vulsrepo/dist/cgi/getfilelist.cgi from the browser.  JSON will be returned if normal.
![image](https://cloud.githubusercontent.com/assets/8981769/25933642/56206160-3653-11e7-96c7-f9dc6db4e350.png)

If the above survey results are different, please check the Readme procedure again.

**Comment by Colbize** [comment]
Thank you, after much debugging turns out SELinux was enabled.

```
$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```

Had to run [specifically](https://www.server-world.info/en/note?os=CentOS_7&p=httpd&f=2):
```
[root@www ~]# chcon -R -t httpd_sys_script_exec_t /var/www/html/vulsrepo
[root@www ~]# semanage fcontext -a -t httpd_sys_script_exec_t /var/www/html/vulsrepo
```
